- name: Install Nginx
  hosts: all
  become: true
  tasks:
    - name: Add Nginx repository
      yum_repository:
        name: nginx
        description: Nginx Repository
        baseurl: https://nginx.org/packages/centos/$releasever/$basearch/
        gpgcheck: true
        gpgkey: https://nginx.org/keys/nginx_signing.key
        enabled: true
    - name: Install Nginx
      yum:
        name: nginx
        state: present
    - name: Add index page
      template:
        src: index.html
        dest: /usr/share/nginx/html/index.html
    - name: Start Nginx
      service:
        name: nginx
        state: started
